### ISSUE TITLE
Add a basic set of monsters

### ISSUE THREAD

**Issue by gilles-leblanc** [gilles-leblanc/gameproject#17]
Right now, there is only the goblin that exists as a monster. Add a basic set of monster that while won't represent the whole set of monsters that need to be defined for the game, will allow preliminary testing/playing.

Say about 5 types of monsters more or less.

This could also be the right time to introduce a proper monster base class if need be.

**Comment by gilles-leblanc** [comment]
I have started working on this issue.

**Comment by shawn42** [comment]
What's the best way to "play" the game at the moment? How are these monsters are used or seen in the game?

**Comment by gilles-leblanc** [comment]
The best way to play right now is calling `ruby map_explorer`. While in the map explorer you can walk around the map, enter cities and dungeons and some doors in cities should output something in the shell to let you know you would have entered a shop.

The game is in a very early stage that these monsters aren't used in game. 

I have developed several things in parallel (map generation, ui and the rules engine). You can test battles (in command line form) by going to /Rules and calling `ruby battle_coordinator_test.rb`. Here you can run a fight, currently a party composed of 1 knight and 1 sorcerer fighting against 2 goblins. 

Since this is what combat looked like in the game I am emulating (http://static2.cdn.ubi.com/emea/gamesites/mm/screen/mm/mm2_3_tn.jpg), the command line fight is not far from where I will end up. 

In the game you will be presented with your party, the mobs and the actions you can take. Each monster or player acting in turn. The results of actions displayed in text. In the screenshot I linked, the scene represented is just before a battle starts when you decide if you want to fight or run. 

If you would fight the game would ask you what a player did on his turn and when you chose for example `Fight` it would ask which target and then output a text message like : `Sir Felgar swings at Skeleton and misses!`.

While I want to make some improvements over the system in Might and Magic 2, I still want to be in the same spirit.

**Comment by shawn42** [comment]
Ah, great. Thanks.  So there are two good candidates for rake tasks. Then rake -T could tell me this instead of github   ;)

**Comment by gilles-leblanc** [comment]
Your right it would be a lot better! 

I've only done Ruby in my spare time so I'm not used to working with Rake, rspec, etc. so I'm missing out on a lot of stuff like this. I'm always happy when people point these out to me. 

Thanks.

**Comment by shawn42** [comment]
No problem!
