### ISSUE TITLE
Integrate Bundler to manage dependencies.

### ISSUE THREAD

**Issue by gilles-leblanc** [gilles-leblanc/gameproject#23]

**Comment by shawn42** [comment]
https://github.com/gilles-leblanc/gameproject/pull/24

**Comment by gilles-leblanc** [comment]
Thanks for the pull request. Also you really cleaned up the Rakefile good.

**Comment by shawn42** [comment]
Glad to help. I've been following your project for a while, mostly the map generation stuff. I'd like to reuse it in a different game someday.  :)
