### ISSUE TITLE
Random name generator sometimes throws exception

### ISSUE THREAD

**Issue by gilles-leblanc** [gilles-leblanc/gameproject#29]
Sometimes we receive this exception with the random name generator. 
`*** Exception in get_last_letter with z and a.`

It can happen pretty much anywhere name generation is used. But it happens very rarely. 

The first thing would to find out how to reproduce this issue consistently.

**Comment by shawn42** [comment]
Update the code to also print out the backtrace so we can know what went wrong. I didn't see any tests for this part of the code, did I just miss them? If not, some test cases may shine some light on the problem.
